version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - mverteuil
  ignore:
  - dependency-name: boto3
    versions:
    - "> 1.9.163, < 1.10"
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
    - 2.12.0
    - 2.12.1
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: click
    versions:
    - 7.1.2
