repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort python imports
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.0
    hooks:
      - id: toml-sort
        name: Sort TOML files
        exclude: ^poetry\.lock$
        args:
          - -i
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
        name: Fix UTF-8 byte order marker
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude_types: [pofile]
      - id: end-of-file-fixer
      - id: check-ast
        name: Python syntax check
      - id: debug-statements
        name: Python debug statement check
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Blacken python source
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        name: Yamllint check
        args: [-c=.yamllint.yaml]
  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry check
        entry: poetry check
        files: (pyproject\.toml|poetry\.lock)$
        language: python
        pass_filenames: false
        additional_dependencies: [poetry]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake8 check
